# Generated by Django 5.0.4 on 2024-05-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='menuitemcategory',
            options={'verbose_name': 'MenuItem Category', 'verbose_name_plural': 'MenuItem Categories'},
        ),
    ]
